export const LOAD_SCHOOLS_SUCCESS = 'LOAD_SCHOOLS_SUCCESS';

export const CREATE_SCHOOL_SUCCESS = 'CREATE_SCHOOL_SUCCESS';

export const LOAD_SCHOOL_SUCCESS = 'LOAD_SCHOOL_SUCCESS';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

export const UPDATE_SCHOOL_SUCCESS = 'UPDATE_SCHOOL_SUCCESS';

export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';

export const DELETE_SCHOOL_SUCCESS = 'DELETE_SCHOOL_SUCCESS';
